name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        id: test_step
        continue-on-error: true
        run: npm test
      
      # Fix for Rollup optional dependencies issue
      - name: Fix dependencies and retry tests
        if: steps.test_step.outcome == 'failure'
        run: |
          echo "First test attempt failed, trying to fix dependencies..."
          rm -rf node_modules package-lock.json
          npm install
          npm test
      
      - name: Run build
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.node-version }}
          path: dist/
          if-no-files-found: error

  publish:
    name: Publish to npm
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-22.x
          path: dist/
      
      - name: Verify version consistency
        id: verify_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" == "$PKG_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) matches package.json version ($PKG_VERSION)."
            echo "versions_match=true" >> $GITHUB_OUTPUT
          else
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PKG_VERSION)."
            echo "versions_match=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Publish to npm
        if: steps.verify_version.outputs.versions_match == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 